package:
    name: phaser
    version: 1.1.1

source:
    path: phaser-1.1.1

build:
    number: 0

requirements:
    build:
        - python
        - bcftools 
        - bedtools 
        - intervaltree
        - setuptools
        - cython
        - scipy
        - pysam
        - pandas
    run:
        - python
