package:
    name: phaser
    version: 1.1.1

source:
    path: .

build:
    number: 1

requirements:
    build:
        - python
        - bcftools 
        - bedtools 
        - intervaltree
        - setuptools
        - cython
        - scipy
        - pysam
        - pandas
    run:
        - python
